Upgrades to pytorch 1.8.1
Fix the error:
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling 'cublasCreate(handle)'
See this issue for further details:
https://github.com/pytorch/pytorch/issues/53336